---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  pre-commit:
    uses: miikkak/workflows/.github/workflows/pr-check.yml@7b4779e095ab7dbd47cd37b6b28424035b2a8752 # main
    secrets: inherit
