---
name: Release Label

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  release-label:
    name: Release Label Check
    uses: miikkak/workflows/.github/workflows/check-release-label.yml@7b4779e095ab7dbd47cd37b6b28424035b2a8752 # main
    permissions:
      contents: read
      pull-requests: read
