---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@7b4779e095ab7dbd47cd37b6b28424035b2a8752 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
